### ISSUE TITLE
username dosn't appear!

### ISSUE THREAD

**Issue by aml987** [GavickPro/Magazine-Free-Joomla-Template#8]
When I login, it's appear just my account link, how can I appear: Welcome Aml Salman?

**Comment by bkrztuk** [comment]
It is impossible without template code modification, you need to use Joomla API to get current username. There is no ready solution which I can provide you here because it is necessary to create some PHP code for the login button area.

I've marked this as a enhancement for future template version but I'm not sure whether we add this feature. This is a custom work which is beyond of our standard technical support. If you are interested in a paid custom work, please create a ticket here: https://www.gavick.com/supportdesk/index.php?/Tickets/Submit in the technical support department with prefix "[CUSTOM WORK]" in the title. Please remember to provide the back-end access, FTP access and URL to your website. We will inform you about the estimated price for this custom work.
